"""
upc_index.py

Loads the pre-built UPC index into memory at startup and provides a fast
binary search to find the nearest known UPC to any generated candidate.

The index is a sorted flat file of 13-digit EAN codes, one per line,
generated by build_upc_index.py. Loading ~3M codes takes roughly 1-2
seconds at startup and uses about 200MB of memory.
"""

import bisect
import os

# ── Index path ────────────────────────────────────────────────────────────────

INDEX_FILE = os.path.join(
    os.path.dirname(__file__),
    'data',
    'upc_index.txt',
)

# ── Module-level index — loaded once at startup ───────────────────────────────

_index: list[int] | None = None


def _load_index() -> list[int]:
    """
    Read the UPC index file and return a sorted list of integers.
    Integers are faster to bisect and compare than strings.
    """
    if not os.path.exists(INDEX_FILE):
        raise FileNotFoundError(
            f'UPC index not found at {INDEX_FILE}. '
            f'Run build_upc_index.py to generate it.'
        )

    codes = []
    with open(INDEX_FILE, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    codes.append(int(line))
                except ValueError:
                    continue

    if not codes:
        raise ValueError('UPC index is empty.')

    return sorted(codes)


def get_index() -> list[int]:
    """Return the loaded index, initialising it on first call."""
    global _index
    if _index is None:
        _index = _load_index()
    return _index


# ── Search ────────────────────────────────────────────────────────────────────

def find_nearest_upc(upc: str, n_candidates: int = 3) -> list[str]:
    """
    Find the n nearest UPCs in the index to the given code.

    Uses binary search (O log n) to locate the insertion point, then
    checks a small window around it to find the closest numeric neighbours.

    Returns a list of 13-digit EAN strings, closest first.
    """
    index = get_index()
    target = int(upc.zfill(13))

    # Binary search for insertion point
    pos = bisect.bisect_left(index, target)

    # Collect candidates from a window around the insertion point
    # Window size of n+1 each side guarantees we catch the n closest
    window_start = max(0, pos - (n_candidates + 1))
    window_end   = min(len(index), pos + (n_candidates + 1))
    window       = index[window_start:window_end]

    # Sort window by numeric distance from target
    window.sort(key=lambda x: abs(x - target))

    # Return as zero-padded 13-digit strings
    return [str(c).zfill(13) for c in window[:n_candidates]]